### ISSUE TITLE
feature request: making it fully "portable"

### ISSUE THREAD

**Issue by MikeHuebschen** [zertovitch/lea#1]
Thank you for this btw. Is it possible to make LEA fully portable (I am thinking of thumb drives)? Without registry entries and such things. Some built-in help for HAT would also be useful.

**Comment by zertovitch** [comment]
It is possible, and the "technology" exists already in another application made with the same toolset: AZip ( https://github.com/zertovitch/azip , https://azip.sourceforge.io/ ). -> Added to the to-do list.

Regarding the help for HAT, I guess you would like something more than what you get with menu Action -> Code sample -> Compatibility -> hat.ads ?

**Comment by zertovitch** [comment]
Stealth mode (LEA running without using registry) was added in commit b59ef3ef330585818df83c54ff3e00ce9aaaab2a.
The help file (visible through F1) contains a new section about it.
Incidentally, the section about HAT was updated (contained the old name, HAL).
